version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_DSN=postgres://postgres:password@db:5432/seccamp
    depends_on:
      - db
    ports:
      - 8080:8080
        
  db:
    image: postgres:15.3
    # container_name: postgres
    # ports:
    #   - 5432
    volumes:
      - $PWD/misc/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: seccamp
# $ docker run --rm -it -p 5432:5432 -e POSTGRES_PASSWORD=password -e POSTGRES_DB=seccamp -v $PWD/misc/sql:/docker-entrypoint-initdb.d postgres:15.3
# DATABASE_DSN=postgres://postgres:password@localhost:5432/seccamp go run cmd/server/main.go
