apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
        - name: goapp
          image: ryohz/seccamp2023b3-goapplication
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: goapp-secret
                  key: database-dsn
---
apiVersion: v1
kind: Service
metadata:
  name: goapp-service
  labels:
    app: goapp
spec:
  # type: NodePort
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      # nodePort: 30080
