apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:bullseye
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_DB
              value: seccamp

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb
data:
  init.sh:
    "#!/bin/bash\n\nset -e\n\npsql -v ON_ERROR_STOP=1 --username \"$POSTGRES_USER\"
    --dbname \"$POSTGRES_DB\" <<-EOSQL\n  CREATE TABLE books (\n    id integer,\n
    \   title varchar(255)\n  );\n  \n  INSERT INTO books VALUES (1, 'Security Camp
    101');\nEOSQL\n"

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
